### ISSUE TITLE
Update code for new opencv?

### ISSUE THREAD

**Issue by quintendewilde** [benhowell/examples#2]
Hi I would like to use your code to capture ip cam images, but I get opencv errors .

```
OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /feedstock_root/build_artefacts/work/opencv-3.1.0/modules/highgui/src/window.cpp, line 545
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/quinten/anaconda2/envs/capture/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/quinten/anaconda2/envs/capture/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "capture.py", line 34, in run
    cv2.imshow('cam',img)
error: /feedstock_root/build_artefacts/work/opencv-3.1.0/modules/highgui/src/window.cpp:545: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage
```

**Comment by benhowell** [comment]
Hi, I'm no longer maintaining this code as it was only written as an example for a blog post 3 or so years ago.
